### ISSUE TITLE
Build fails on Windows 7

### ISSUE THREAD

**Issue by TimothyWrightSoftware** [ValveSoftware/vogl#205]
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/voglcore/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/voglgen/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/voglcommon/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/voglreplay/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/voglbench/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/vogltrace/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/vogltest/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/glxspheres/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/vogleditor/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/extlib/pxfmt/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/game_dev/3rd/vogl/vogl_build/src/ktxtool/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: voglcore, Configuration: Debug x64 ------
3>------ Build started: Project: copy_deps, Configuration: Debug x64 ------
2>  Building Custom Rule C:/game_dev/3rd/vogl/src/voglcore/CMakeLists.txt
3>  Building Custom Rule C:/game_dev/3rd/vogl/src/voglcore/CMakeLists.txt
3>  CMake does not need to re-run because C:\game_dev\3rd\vogl\vogl_build\src\voglcore\CMakeFiles\generate.stamp is up-to-date.
2>  CMake does not need to re-run because C:\game_dev\3rd\vogl\vogl_build\src\voglcore\CMakeFiles\generate.stamp is up-to-date.
3>  Copying necessary DLLs to output directory.
3>  Error copying file (if different) from "C:/game_dev/3rd/vogl/src/../../external/windows/pthreads.2/dll/x64/pthreadVC2.dll" to "C:/game_dev/3rd/vogl/vogl_build/Debug".
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1.
2>  vogl_assert.cpp
2>  vogl_checksum.cpp
2>  vogl_colorized_console.cpp
2>  vogl_command_line_params.cpp
2>  vogl_console.cpp
2>  vogl_core.cpp
2>  vogl_data_stream.cpp
2>  vogl_dxt1.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_checksum.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_core.cpp)
2>  vogl_dxt5a.cpp
2>  vogl_dxt.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_assert.cpp)
2>  vogl_dxt_fast.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_console.cpp)
2>  vogl_dxt_image.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_colorized_console.cpp)
2>  vogl_dynamic_module.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_command_line_params.cpp)
2>  vogl_dynamic_string.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_data_stream.cpp)
2>  vogl_file_utils.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_dxt1.cpp)
2>  vogl_find_files.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_dxt.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_dxt5a.cpp)
2>  vogl_hash.cpp
2>  vogl_hash_map.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_dxt_fast.cpp)
2>  vogl_image_utils.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_dxt_image.cpp)
2>  vogl_jpgd.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_dynamic_module.cpp)
2>  vogl_jpge.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_file_utils.cpp)
2>  vogl_json.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_dynamic_string.cpp)
2>  vogl_ktx_texture.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_find_files.cpp)
2>  vogl.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_hash_map.cpp)
2>  vogl_math.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_image_utils.cpp)
2>  vogl_mem.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_jpgd.cpp)
2>  vogl_miniz.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_hash.cpp)
2>  vogl_miniz_zip.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_jpge.cpp)
2>  vogl_miniz_zip_test.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_json.cpp)
2>  vogl_pixel_format.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_ktx_texture.cpp)
2>  vogl_platform.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl.cpp)
2>  vogl_port.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_math.cpp)
2>  vogl_rand.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_mem.cpp)
2>  vogl_resample_filters.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_miniz.cpp)
2>  vogl_resampler.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_miniz_zip.cpp)
2>  vogl_ryg_dxt.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_miniz_zip_test.cpp)
2>  vogl_sparse_bit_array.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_pixel_format.cpp)
2>  vogl_stb_image.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_platform.cpp)
2>  vogl_strutils.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_port.cpp)
2>  vogl_texture_file_types.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_rand.cpp)
2>  vogl_threaded_resampler.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_resample_filters.cpp)
2>  vogl_threading_pthreads.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_resampler.cpp)
2>  vogl_timer.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_ryg_dxt.cpp)
2>  vogl_utils.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_sparse_bit_array.cpp)
2>  vogl_value.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_stb_image.cpp)
2>  vogl_vector.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_strutils.cpp)
2>  vogl_etc.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_texture_file_types.cpp)
2>  vogl_rg_etc1.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_threaded_resampler.cpp)
2>  vogl_regex.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_threading_pthreads.cpp)
2>  vogl_map.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_timer.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_utils.cpp)
2>  vogl_md5.cpp
2>  vogl_introsort.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_value.cpp)
2>  vogl_uuid.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_vector.cpp)
2>  vogl_backtrace.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_etc.cpp)
2>  stb_malloc.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_rg_etc1.cpp)
2>  vogl_rh_hash_map.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_regex.cpp)
2>  vogl_object_pool.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_introsort.cpp)
2>  vogl_port_windows.cpp
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_map.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_md5.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_uuid.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_backtrace.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\stb_malloc.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_rh_hash_map.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_object_pool.cpp)
2>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcore\vogl_port_windows.cpp)
4>------ Build started: Project: voglgen, Configuration: Debug x64 ------
4>  Building Custom Rule C:/game_dev/3rd/vogl/src/voglgen/CMakeLists.txt
4>  CMake does not need to re-run because C:\game_dev\3rd\vogl\vogl_build\src\voglgen\CMakeFiles\generate.stamp is up-to-date.
4>  voglgen.cpp
4>  tinyxml2.cpp
4>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglgen\voglgen.cpp)
5>------ Build started: Project: voglgen_make_inc, Configuration: Debug x64 ------
5>  Building Custom Rule C:/game_dev/3rd/vogl/src/voglgen/CMakeLists.txt
5>  CMake does not need to re-run because C:\game_dev\3rd\vogl\vogl_build\src\voglgen\CMakeFiles\generate.stamp is up-to-date.
5>  Running voglgen to generate include and linker files for other targets
5>  '..\..\Debug\voglgen64.exe' is not recognized as an internal or external command,
5>  operable program or batch file.
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 9009.
6>------ Build started: Project: voglcommon, Configuration: Debug x64 ------
6>  Building Custom Rule C:/game_dev/3rd/vogl/src/voglcommon/CMakeLists.txt
6>  CMake does not need to re-run because C:\game_dev\3rd\vogl\vogl_build\src\voglcommon\CMakeFiles\generate.stamp is up-to-date.
6>  gl_types.cpp
6>  vogl_ctypes.cpp
6>  vogl_gl_utils.cpp
6>  vogl_entrypoints.cpp
6>  vogl_trace_packet.cpp
6>  vogl_trace_file_reader.cpp
6>  vogl_trace_file_writer.cpp
6>  vogl_context_info.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_gl_utils.cpp)
6>  vogl_blob_manager.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_ctypes.cpp)
6>  vogl_texture_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_trace_packet.cpp)
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_context_info.cpp)
6>  vogl_general_context_state.cpp
6>  vogl_fbo_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_entrypoints.cpp)
6>  vogl_renderbuffer_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_trace_file_reader.cpp)
6>  vogl_state_vector.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_trace_file_writer.cpp)
6>  vogl_texture_format.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_blob_manager.cpp)
6>  vogl_sampler_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_general_context_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_fbo_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_renderbuffer_state.cpp)
6>  vogl_buffer_state.cpp
6>  vogl_query_state.cpp
6>  vogl_shader_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_state_vector.cpp)
6>  vogl_program_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_texture_format.cpp)
6>  vogl_fs_preprocessor.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_sampler_state.cpp)
6>  vogl_gl_object.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_buffer_state.cpp)
6>  vogl_gl_state_snapshot.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_shader_state.cpp)
6>  vogl_vao_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_program_state.cpp)
6>  vogl_sso_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_gl_object.cpp)
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_fs_preprocessor.cpp)
6>  vogl_sync_object.cpp
6>  vogl_replay_window.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_vao_state.cpp)
6>  vogl_gl_replayer.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_sso_state.cpp)
6>  vogl_framebuffer_capturer.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_replay_window.cpp)
6>  vogl_material_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_framebuffer_capturer.cpp)
6>  vogl_light_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\gl_types.cpp)
6>  vogl_texenv_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_texture_state.cpp)
6>  vogl_display_list_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_query_state.cpp)
6>  vogl_matrix_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_gl_state_snapshot.cpp)
6>  vogl_common.cpp
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_sync_object.cpp)
6>  vogl_current_vertex_attrib_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_common.cpp)
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_gl_replayer.cpp)
6>  vogl_arb_program_state.cpp
6>  vogl_handle_tracker.cpp
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_current_vertex_attrib_state.cpp)
6>  vogl_default_framebuffer_state.cpp
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_material_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_arb_program_state.cpp)
6>  vogl_shader_utils.cpp
6>  vogl_msaa_texture.cpp
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_light_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_handle_tracker.cpp)
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_texenv_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_display_list_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_matrix_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_default_framebuffer_state.cpp)
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_shader_utils.cpp)
6>c:\game_dev\3rd\vogl\src\voglcore\vogl_threading_pthreads.h(40): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglcommon\vogl_msaa_texture.cpp)
7>------ Build started: Project: vogl, Configuration: Debug x64 ------
7>  Building Custom Rule C:/game_dev/3rd/vogl/src/voglreplay/CMakeLists.txt
7>  CMake does not need to re-run because C:\game_dev\3rd\vogl\vogl_build\src\voglreplay\CMakeFiles\generate.stamp is up-to-date.
7>  vogl_replay_tool.cpp
7>  replay_tool_dump.cpp
7>  replay_tool_parse.cpp
7>  replay_tool_info.cpp
7>  replay_tool_json.cpp
7>  replay_tool_find.cpp
7>  replay_tool_compare_hash.cpp
7>  replay_tool_replay.cpp
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_compare_hash.cpp)
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_dump.cpp)
7>  replay_tool_syms.cpp
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_find.cpp)
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_info.cpp)
7>  replay_tool_trace.cpp
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_parse.cpp)
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_json.cpp)
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\vogl_replay_tool.cpp)
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_replay.cpp)
7>c:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_syms.cpp)
7>C:\game_dev\3rd\vogl\src\voglcommon\vogl_common.h(44): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory (..\..\..\src\voglreplay\replay_tool_trace.cpp)
========== Build: 1 succeeded, 6 failed, 0 up-to-date, 0 skipped ==========

**Comment by openforeveryone** [comment]
It looks like you have not installed pthreads (or not in the correct place). I have written up some slightly more detailed build instructions here: https://github.com/ValveSoftware/vogl/wiki/Installing-%28Windows%29 . Hope this helps.

**Comment by TimothyWrightSoftware** [comment]
Thank you for the link.  The instructions I was using to build didn't have all this stuff.  I will try it out soon.
