### ISSUE TITLE
'Make -j 10' is "ugly"

### ISSUE THREAD

**Issue by Chocanto** [ValveSoftware/vogl#213]
In the readme at the section *Linux* (https://github.com/ValveSoftware/vogl#linux) you can see in the list of command this one : 
```
make -j 10
```

But the make manual, about -j, tell (https://www.gnu.org/software/make/manual/html_node/Parallel.html) : 
> If there is nothing looking like an integer after the ‘-j’ option, there is no limit on the number of job slots.

So why not just execute `make -j` ?

**Comment by Plagman** [comment]
Because that will most likely cause your machine to swap unlike -j10, depending on the size of the project.
